### PR TITLE
added dashboard documentation

### PR DESCRIPTION
**Pull request by thomashopkins32**
Documentation detailing `nsls2forge_utils`'s `dashboard` command and how to use it.

### CODE REVIEW

**Comment by mrakitin** [comment]
The conflict should be resolved by rebasing on master. Please check https://github.com/k88hudson/git-flight-rules or ping me in the morning :)

**Comment by thomashopkins32** [comment]
Will do, I was trying that for the other merges I made and couldn't get it to work correctly. So I just resolved the conflicts here on GitHub instead.

**Comment by mrakitin** [comment]
Let's actually have a call either later today or tomorrow. I'd like you to get familiar with the CLI way to resolve it. It's a pretty common use-case while working on git repos, and this skill can be pretty useful in your future contributions to big projects.

**Comment by thomashopkins32** [comment]
Sounds good, tomorrow at 10 am works great. Thanks!

**Pull request merged**
