### PR TITLE
document method to calculate SHA256 digest

### LINKED ISSUE #5: describe how to get SHA256 digest
In section "Manually create a recipe or use the existing recipe" there should be instructions for calculating the SHA256 digest from a source archive.

### PR DESCRIPTION
**Pull request by jklynch**
This PR adds instructions for calculating SHA256 digest required for a recipe. Closes #5.

Here is what this PR looks like:

nsls-ii-docs-sha256

### CODE REVIEW

**Review by mrakitin — COMMENTED** [review]
Looks good, thanks @jklynch!

Do you mind adding the following to the PR body:
```
Closes #5.
```
I would also extend the example with the downloading step (`wget ...`).

**Comment by jklynch** [comment]
Here is the updated version with `wget`:

image

**Comment by mrakitin** [comment]
@jklynch, did you push the updated text?

**Comment by jklynch** [comment]
I spent so much time on the screenshot I forgot all about pushing the changes.

**Review by mrakitin — APPROVED** [review]
Thanks a lot, @jklynch!

**Pull request merged**
